WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10680ca30>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/80f8e93b4f92326c377fc0103022c0b0/title
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10680c850>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/80f8e93b4f92326c377fc0103022c0b0/title
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10680c7c0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/80f8e93b4f92326c377fc0103022c0b0/title